services:
  credit.customers:
    image: credit.customers
    build:
      context: .
      dockerfile: credit.customers/Dockerfile
    ports:
      - "5101:8080"
    environment:
      Jwt__Key: ${JWT_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  credit.loans:
    image: credit.loans
    build:
      context: .
      dockerfile: credit.loans/Dockerfile
    ports:
      - "5102:8080"
    environment:
      Jwt__Key: ${JWT_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  credit.identity:
    image: credit.identity
    build:
      context: .
      dockerfile: credit.identity/Dockerfile
    ports:
      - "5103:8080"
    environment:
      Jwt__Key: ${JWT_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s
    
volumes:
  postgres-data: